# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: faster-whisper-medium-en-cpu
spec:
  features: [SpeechToText]
  url: hf://Systran/faster-whisper-medium.en
  engine: FasterWhisper
  minReplicas: 0
  resourceProfile: cpu:1
