# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: nomic-embed-text-cpu
spec:
  features: [TextEmbedding]
  url: ollama://nomic-embed-text
  engine: OLlama
  minReplicas: 0
  resourceProfile: cpu:1
