# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: qwen2.5-7b-cpu
spec:
  features: [TextGeneration]
  url: ollama://qwen2.5:7b
  engine: OLlama
  minReplicas: 0
  resourceProfile: cpu:2
