apiVersion: v1
kind: Service
metadata:
  name: lingo
  namespace: default
spec:
  selector:
    app: lingo
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: stats
      protocol: TCP
      port: 8083
  type: NodePort
