apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingo
  labels:
    app: lingo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lingo
  template:
    metadata:
      labels:
        app: lingo
    spec:
      serviceAccountName: lingo
      containers:
        - name: main
          image: us-central1-docker.pkg.dev/substratus-dev/substratus/lingo
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
