{{- if .Values.secrets.huggingface.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeai.fullname" . }}-huggingface
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  token: {{ .Values.secrets.huggingface.token | b64enc }}
{{- end }}